FROM node:slim

COPY public/ /app/public
COPY src/ /app/src
COPY package.json /app/

WORKDIR /app

ENV APP_URL=__APP_URL__
ENV MAP_BOXGL=__MAP_BOXGL__

RUN echo "APP_URL=$APP_URL">.env
RUN echo "MAP_BOXGL=$MAP_BOXGL">>.env


RUN npm install

EXPOSE 3000:3000

CMD ["npm", "start"]